-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 01-11-2024 a las 01:17:21
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `recibo_db`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `recibos`
--

CREATE TABLE `recibos` (
  `id` int(11) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `contenido` text NOT NULL,
  `numero_recibo` varchar(20) DEFAULT NULL,
  `deuda_anterior` varchar(20) DEFAULT NULL,
  `pago_mes_actual` varchar(20) DEFAULT NULL,
  `deuda_total` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `recibos`
--

INSERT INTO `recibos` (`id`, `nombre`, `contenido`, `numero_recibo`, `deuda_anterior`, `pago_mes_actual`, `deuda_total`) VALUES
(255, 'recibo_1.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 34 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ VERA GERMAN\nDatos del suministro de consumo Importes facturados\nLectura actual 5733 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5671 Cargo Fijo S/ 3.53\nDiferencia Lectura 62 Energia activa S/ 46.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 50.03\nI.G.V S/ 9.01\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 91.97\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 64.54\nFecha de corte 20-Oct Deuda Total. S/ 156.51\nPeriodo comercial Set-24 Recibo N° 34\nHERNANDEZ VERA GERMAN\nPago Mes Actual S/ 64.54\nCaserío El muerto S/N Deuda total. S/ 156.51\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(256, 'recibo_2.pdf', 'Comité de Electrificación Las Norias 126\nRecibo N° 108 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO NUNURA GUILLERMO\nDatos del suministro de consumo Importes facturados\nLectura actual 4620 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4500 Cargo Fijo S/ 3.53\nDiferencia Lectura 120 Energia activa S/ 90.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 93.53\nI.G.V S/ 16.84\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 115.87\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 108\nSOPLOPUCO NUNURA GUILLERMO\nPago Mes Actual S/ 115.87\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(257, 'recibo_3.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 143 Mes Actual Set-24\nOlmos/ Las Norias\nELSA QUINDE MIJAHUANCA\nDatos del suministro de consumo Importes facturados\nLectura actual 131 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 114 Cargo Fijo S/ 3.53\nDiferencia Lectura 17 Energia activa S/ 12.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 16.28\nI.G.V S/ 2.93\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 24.71\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 143\nELSA QUINDE MIJAHUANCA\nPago Mes Actual S/ 24.71\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(258, 'recibo_4.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 142 Mes Actual Set-24\nOlmos/ Las Norias\nMARIELA SANCHEZ VIDAURRE\nDatos del suministro de consumo Importes facturados\nLectura actual 45 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 33 Cargo Fijo S/ 3.53\nDiferencia Lectura 12 Energia activa S/ 9.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 12.53\nI.G.V S/ 2.26\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 20.29\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 142\nMARIELA SANCHEZ VIDAURRE\nPago Mes Actual S/ 20.29\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(259, 'recibo_5.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 141 Mes Actual Set-24\nOlmos/ Las Norias\nMARTINEZ ALARCON SARA\nDatos del suministro de consumo Importes facturados\nLectura actual 472 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 424 Cargo Fijo S/ 3.53\nDiferencia Lectura 48 Energia activa S/ 36.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 39.53\nI.G.V S/ 7.12\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 52.15\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 141\nMARTINEZ ALARCON SARA\nPago Mes Actual S/ 52.15\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(260, 'recibo_6.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 140 Mes Actual Set-24\nOlmos/ Las Norias\nDARIO BENITES TESÉN\nDatos del suministro de consumo Importes facturados\nLectura actual 38 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 31 Cargo Fijo S/ 3.53\nDiferencia Lectura 7 Energia activa S/ 5.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 8.78\nI.G.V S/ 1.58\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 15.86\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 140\nDARIO BENITES TESÉN\nPago Mes Actual S/ 15.86\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(261, 'recibo_7.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 139 Mes Actual Set-24\nOlmos/ Las Norias\nLILIANA TORRES HURTADO\nDatos del suministro de consumo Importes facturados\nLectura actual 300 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 282 Cargo Fijo S/ 3.53\nDiferencia Lectura 18 Energia activa S/ 13.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 17.03\nI.G.V S/ 3.07\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 25.60\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 139\nLILIANA TORRES HURTADO\nPago Mes Actual S/ 25.60\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(262, 'recibo_8.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 138 Mes Actual Set-24\nOlmos/ Las Norias\nYAJAHUANCA CORREA ALEJANDRO\nDatos del suministro de consumo Importes facturados\nLectura actual 158 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 158 Cargo Fijo S/ 3.53\nDiferencia Lectura 0 Energia activa S/ 0.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 3.53\nI.G.V S/ 0.64\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 9.67\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 138\nYAJAHUANCA CORREA ALEJANDRO\nPago Mes Actual S/ 9.67\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(263, 'recibo_9.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 137 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES MIO SILVIA\nDatos del suministro de consumo Importes facturados\nLectura actual 2241 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2126 Cargo Fijo S/ 3.53\nDiferencia Lectura 115 Energia activa S/ 86.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 89.78\nI.G.V S/ 16.16\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Junio - Julio - Agosto S/ 346.72\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 111.44\nFecha de corte 20-Oct Deuda Total. S/ 458.16\nPeriodo comercial Set-24 Recibo N° 137\nBENITES MIO SILVIA\nPago Mes Actual S/ 111.44\nCaserío El muerto S/N Deuda total. S/ 458.16\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(264, 'recibo_10.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 136 Mes Actual Set-24\nOlmos/ Las Norias\nPUPUCHE ESTRADA KEVIN\nDatos del suministro de consumo Importes facturados\nLectura actual 1681 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1582 Cargo Fijo S/ 3.53\nDiferencia Lectura 99 Energia activa S/ 74.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 77.78\nI.G.V S/ 14.00\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 97.28\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 136\nPUPUCHE ESTRADA KEVIN\nPago Mes Actual S/ 97.28\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(265, 'recibo_11.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 134 Mes Actual Set-24\nOlmos/ Las Norias\nMAZA MIO GIAN GABRIEL\nDatos del suministro de consumo Importes facturados\nLectura actual 1025 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 997 Cargo Fijo S/ 3.53\nDiferencia Lectura 28 Energia activa S/ 21.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 24.53\nI.G.V S/ 4.42\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 34.45\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 134\nMAZA MIO GIAN GABRIEL\nPago Mes Actual S/ 34.45\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(266, 'recibo_12.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 133 Mes Actual Set-24\nOlmos/ Las Norias\nSERRATO MONJA JORDY\nDatos del suministro de consumo Importes facturados\nLectura actual 450 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 426 Cargo Fijo S/ 3.53\nDiferencia Lectura 24 Energia activa S/ 18.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 21.53\nI.G.V S/ 3.88\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 36.22\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 30.91\nFecha de corte 20-Oct Deuda Total. S/ 67.13\nPeriodo comercial Set-24 Recibo N° 133\nSERRATO MONJA JORDY\nPago Mes Actual S/ 30.91\nCaserío El muerto S/N Deuda total. S/ 67.13\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(267, 'recibo_13.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 132 Mes Actual Set-24\nOlmos/ Las Norias\nMÍO MACO JAIME\nDatos del suministro de consumo Importes facturados\nLectura actual 19 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 19 Cargo Fijo S/ 3.53\nDiferencia Lectura 0 Energia activa S/ 0.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 3.53\nI.G.V S/ 0.64\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 9.67\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 132\nMÍO MACO JAIME\nPago Mes Actual S/ 9.67\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(268, 'recibo_14.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 130 Mes Actual Set-24\nOlmos/ Las Norias\nNUNURA SOPLOPUCO JUAN MANUEL\nDatos del suministro de consumo Importes facturados\nLectura actual 1744 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1667 Cargo Fijo S/ 3.53\nDiferencia Lectura 77 Energia activa S/ 57.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 61.28\nI.G.V S/ 11.03\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 77.81\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 130\nNUNURA SOPLOPUCO JUAN MANUEL\nPago Mes Actual S/ 77.81\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(269, 'recibo_15.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 129 Mes Actual Set-24\nOlmos/ Las Norias\nSANDRA CHAQUILA CUNIAS\nDatos del suministro de consumo Importes facturados\nLectura actual 860 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 830 Cargo Fijo S/ 3.53\nDiferencia Lectura 30 Energia activa S/ 22.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 26.03\nI.G.V S/ 4.69\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 37.99\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 36.22\nFecha de corte 20-Oct Deuda Total. S/ 74.21\nPeriodo comercial Set-24 Recibo N° 129\nSANDRA CHAQUILA CUNIAS\nPago Mes Actual S/ 36.22\nCaserío El muerto S/N Deuda total. S/ 74.21\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(270, 'recibo_16.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 128 Mes Actual Set-24\nOlmos/ Las Norias\nROSA GAMARRA MORALES\nDatos del suministro de consumo Importes facturados\nLectura actual 3157 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3116 Cargo Fijo S/ 3.53\nDiferencia Lectura 41 Energia activa S/ 30.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 34.28\nI.G.V S/ 6.17\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 45.95\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 128\nROSA GAMARRA MORALES\nPago Mes Actual S/ 45.95\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(271, 'recibo_17.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 126 Mes Actual Set-24\nOlmos/ Las Norias\nCABRERA HERRERA ROGER\nDatos del suministro de consumo Importes facturados\nLectura actual 1186 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1180 Cargo Fijo S/ 3.53\nDiferencia Lectura 6 Energia activa S/ 4.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 8.03\nI.G.V S/ 1.45\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 27.37\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 14.98\nFecha de corte 20-Oct Deuda Total. S/ 42.35\nPeriodo comercial Set-24 Recibo N° 126\nCABRERA HERRERA ROGER\nPago Mes Actual S/ 14.98\nCaserío El muerto S/N Deuda total. S/ 42.35\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(272, 'recibo_18.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 125 Mes Actual Set-24\nOlmos/ Las Norias\nNORMA CAJO\nDatos del suministro de consumo Importes facturados\nLectura actual 3114 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3003 Cargo Fijo S/ 3.53\nDiferencia Lectura 111 Energia activa S/ 83.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 86.78\nI.G.V S/ 15.62\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 85.78\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 107.90\nFecha de corte 20-Oct Deuda Total. S/ 193.68\nPeriodo comercial Set-24 Recibo N° 125\nNORMA CAJO\nPago Mes Actual S/ 107.90\nCaserío El muerto S/N Deuda total. S/ 193.68\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(273, 'recibo_19.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 124 Mes Actual Set-24\nOlmos/ Las Norias\nNUNURA MONJA RICARDO\nDatos del suministro de consumo Importes facturados\nLectura actual 2343 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2225 Cargo Fijo S/ 3.53\nDiferencia Lectura 118 Energia activa S/ 88.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 92.03\nI.G.V S/ 16.57\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 114.10\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 124\nNUNURA MONJA RICARDO\nPago Mes Actual S/ 114.10\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(274, 'recibo_20.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 123 Mes Actual Set-24\nOlmos/ Las Norias\nZUÑIGA HUAMAN CARMEN\nDatos del suministro de consumo Importes facturados\nLectura actual 5135 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5122 Cargo Fijo S/ 3.53\nDiferencia Lectura 13 Energia activa S/ 9.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 13.28\nI.G.V S/ 2.39\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 14.98\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 21.17\nFecha de corte 20-Oct Deuda Total. S/ 36.15\nPeriodo comercial Set-24 Recibo N° 123\nZUÑIGA HUAMAN CARMEN\nPago Mes Actual S/ 21.17\nCaserío El muerto S/N Deuda total. S/ 36.15\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(275, 'recibo_21.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 121 Mes Actual Set-24\nOlmos/ Las Norias\nYAJAHUANCA CORREA CLEIDER\nDatos del suministro de consumo Importes facturados\nLectura actual 304 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 296 Cargo Fijo S/ 3.53\nDiferencia Lectura 8 Energia activa S/ 6.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 9.53\nI.G.V S/ 1.72\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 16.75\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 121\nYAJAHUANCA CORREA CLEIDER\nPago Mes Actual S/ 16.75\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(276, 'recibo_22.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 120 Mes Actual Set-24\nOlmos/ Las Norias\nYAJAHUANCA CORREA SERVANDO\nDatos del suministro de consumo Importes facturados\nLectura actual 2943 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2875 Cargo Fijo S/ 3.53\nDiferencia Lectura 68 Energia activa S/ 51.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 54.53\nI.G.V S/ 9.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 62.77\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 69.85\nFecha de corte 20-Oct Deuda Total. S/ 132.62\nPeriodo comercial Set-24 Recibo N° 120\nYAJAHUANCA CORREA SERVANDO\nPago Mes Actual S/ 69.85\nCaserío El muerto S/N Deuda total. S/ 132.62\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(277, 'recibo_23.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 119 Mes Actual Set-24\nOlmos/ Las Norias\nVILLAREAL DE SOPLOPUCO VIRGINA\nDatos del suministro de consumo Importes facturados\nLectura actual 201 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 189 Cargo Fijo S/ 3.53\nDiferencia Lectura 12 Energia activa S/ 9.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 12.53\nI.G.V S/ 2.26\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 20.29\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 119\nVILLAREAL DE SOPLOPUCO VIRGINA\nPago Mes Actual S/ 20.29\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(278, 'recibo_24.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 118 Mes Actual Set-24\nOlmos/ Las Norias\nVALLEJOS CALLIRGOS MERLY\nDatos del suministro de consumo Importes facturados\nLectura actual 3578 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3510 Cargo Fijo S/ 3.53\nDiferencia Lectura 68 Energia activa S/ 51.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 54.53\nI.G.V S/ 9.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo + junio a agosto S/ 257.00\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 69.85\nFecha de corte 20-Oct Deuda Total. S/ 326.85\nPeriodo comercial Set-24 Recibo N° 118\nVALLEJOS CALLIRGOS MERLY\nPago Mes Actual S/ 69.85\nCaserío El muerto S/N Deuda total. S/ 326.85\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(279, 'recibo_25.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 117 Mes Actual Set-24\nOlmos/ Las Norias\nTESEN MACO JORGE LUIS\nDatos del suministro de consumo Importes facturados\nLectura actual 7983 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 7934 Cargo Fijo S/ 3.53\nDiferencia Lectura 49 Energia activa S/ 36.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 40.28\nI.G.V S/ 7.25\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio + Agosto S/ 133.35\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 53.03\nFecha de corte 20-Oct Deuda Total. S/ 186.38\nPeriodo comercial Set-24 Recibo N° 117\nTESEN MACO JORGE LUIS\nPago Mes Actual S/ 53.03\nCaserío El muerto S/N Deuda total. S/ 186.38\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(280, 'recibo_26.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 116 Mes Actual Set-24\nOlmos/ Las Norias\nSOSA TORRES MATILDE AGRIPINA\nDatos del suministro de consumo Importes facturados\nLectura actual 15750 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 15636 Cargo Fijo S/ 3.53\nDiferencia Lectura 114 Energia activa S/ 85.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 89.03\nI.G.V S/ 16.03\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 96.27\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 110.56\nFecha de corte 20-Oct Deuda Total. S/ 206.83\nPeriodo comercial Set-24 Recibo N° 116\nSOSA TORRES MATILDE AGRIPINA\nPago Mes Actual S/ 110.56\nCaserío El muerto S/N Deuda total. S/ 206.83\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(281, 'recibo_27.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 115 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO VILLAREAL JULIO C\nDatos del suministro de consumo Importes facturados\nLectura actual 2429 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2410 Cargo Fijo S/ 3.53\nDiferencia Lectura 19 Energia activa S/ 14.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 17.78\nI.G.V S/ 3.20\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 26.48\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 115\nSOPLOPUCO VILLAREAL JULIO C\nPago Mes Actual S/ 26.48\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(282, 'recibo_28.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 113 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO REYES JORGE\nDatos del suministro de consumo Importes facturados\nLectura actual 783 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 781 Cargo Fijo S/ 3.53\nDiferencia Lectura 2 Energia activa S/ 1.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 5.03\nI.G.V S/ 0.91\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo + Agosto S/ 221.32\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 11.44\nFecha de corte 20-Oct Deuda Total. S/ 232.76\nPeriodo comercial Set-24 Recibo N° 113\nSOPLOPUCO REYES JORGE\nPago Mes Actual S/ 11.44\nCaserío El muerto S/N Deuda total. S/ 232.76\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(283, 'recibo_29.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 112 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO OLAZABAL FLORENTINO\nDatos del suministro de consumo Importes facturados\nLectura actual 5605 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5559 Cargo Fijo S/ 3.53\nDiferencia Lectura 46 Energia activa S/ 34.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 38.03\nI.G.V S/ 6.85\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 50.38\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 112\nSOPLOPUCO OLAZABAL FLORENTINO\nPago Mes Actual S/ 50.38\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(284, 'recibo_30.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 111 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO ODAR EDILfONSO\nDatos del suministro de consumo Importes facturados\nLectura actual 197 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 141 Cargo Fijo S/ 3.53\nDiferencia Lectura 56 Energia activa S/ 42.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 45.53\nI.G.V S/ 8.20\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Medidor cuota 3/3 S/ 50.00\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 59.23\nFecha de corte 20-Oct Deuda Total. S/ 109.23\nPeriodo comercial Set-24 Recibo N° 111\nSOPLOPUCO ODAR EDILfONSO\nPago Mes Actual S/ 59.23\nCaserío El muerto S/N Deuda total. S/ 109.23\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(285, 'recibo_31.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 110 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO NUNURA MARIA DEL PILA\nDatos del suministro de consumo Importes facturados\nLectura actual 5183 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5127 Cargo Fijo S/ 3.53\nDiferencia Lectura 56 Energia activa S/ 42.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 45.53\nI.G.V S/ 8.20\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 59.23\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 110\nSOPLOPUCO NUNURA MARIA DEL PILA\nPago Mes Actual S/ 59.23\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(286, 'recibo_32.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 109 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO NUNURA MARIA (KIOSKO)\nDatos del suministro de consumo Importes facturados\nLectura actual 220 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 196 Cargo Fijo S/ 3.53\nDiferencia Lectura 24 Energia activa S/ 18.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 21.53\nI.G.V S/ 3.88\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 30.91\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 109\nSOPLOPUCO NUNURA MARIA (KIOSKO)\nPago Mes Actual S/ 30.91\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(287, 'recibo_33.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 107 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO NUNURA ALICIA\nDatos del suministro de consumo Importes facturados\nLectura actual 6777 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 6709 Cargo Fijo S/ 3.53\nDiferencia Lectura 68 Energia activa S/ 51.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 54.53\nI.G.V S/ 9.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 69.85\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 107\nSOPLOPUCO NUNURA ALICIA\nPago Mes Actual S/ 69.85\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(288, 'recibo_34.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 106 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO MIO FELIPE\nDatos del suministro de consumo Importes facturados\nLectura actual 11918 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 11842 Cargo Fijo S/ 3.53\nDiferencia Lectura 76 Energia activa S/ 57.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 60.53\nI.G.V S/ 10.90\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 76.93\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 106\nSOPLOPUCO MIO FELIPE\nPago Mes Actual S/ 76.93\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(289, 'recibo_35.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 105 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO MIO CECILIA\nDatos del suministro de consumo Importes facturados\nLectura actual 4831 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4830 Cargo Fijo S/ 3.53\nDiferencia Lectura 1 Energia activa S/ 0.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 4.28\nI.G.V S/ 0.77\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 10.55\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 10.55\nFecha de corte 20-Oct Deuda Total. S/ 21.10\nPeriodo comercial Set-24 Recibo N° 105\nSOPLOPUCO MIO CECILIA\nPago Mes Actual S/ 10.55\nCaserío El muerto S/N Deuda total. S/ 21.10\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(290, 'recibo_36.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 104 Mes Actual Set-24\nOlmos/ Las Norias\nSOPLOPUCO MAZA GUILLERMO\nDatos del suministro de consumo Importes facturados\nLectura actual 12479 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12363 Cargo Fijo S/ 3.53\nDiferencia Lectura 116 Energia activa S/ 87.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 90.53\nI.G.V S/ 16.30\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 112.33\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 104\nSOPLOPUCO MAZA GUILLERMO\nPago Mes Actual S/ 112.33\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(291, 'recibo_37.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 102 Mes Actual Set-24\nOlmos/ Las Norias\nSOLIS SOPLOPUCO ROOSBEL\nDatos del suministro de consumo Importes facturados\nLectura actual 10295 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10017 Cargo Fijo S/ 3.53\nDiferencia Lectura 278 Energia activa S/ 208.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 212.03\nI.G.V S/ 38.17\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio y agosto S/ 497.23\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 255.70\nFecha de corte 20-Oct Deuda Total. S/ 752.93\nPeriodo comercial Set-24 Recibo N° 102\nSOLIS SOPLOPUCO ROOSBEL\nPago Mes Actual S/ 255.70\nCaserío El muerto S/N Deuda total. S/ 752.93\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(292, 'recibo_38.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 101 Mes Actual Set-24\nOlmos/ Las Norias\nSANCHEZ VIDAURRE NERIDA\nDatos del suministro de consumo Importes facturados\nLectura actual 1528 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1513 Cargo Fijo S/ 3.53\nDiferencia Lectura 15 Energia activa S/ 11.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 14.78\nI.G.V S/ 2.66\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. AGOSTO S/ 24.71\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 22.94\nFecha de corte 20-Oct Deuda Total. S/ 47.65\nPeriodo comercial Set-24 Recibo N° 101\nSANCHEZ VIDAURRE NERIDA\nPago Mes Actual S/ 22.94\nCaserío El muerto S/N Deuda total. S/ 47.65\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(293, 'recibo_39.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 100 Mes Actual Set-24\nOlmos/ Las Norias\nSANCHEZ VIDAURRE SANTOS\nDatos del suministro de consumo Importes facturados\nLectura actual 3818 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3775 Cargo Fijo S/ 3.53\nDiferencia Lectura 43 Energia activa S/ 32.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 35.78\nI.G.V S/ 6.44\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio y Agosto S/ 66.24\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 47.72\nFecha de corte 20-Oct Deuda Total. S/ 113.96\nPeriodo comercial Set-24 Recibo N° 100\nSANCHEZ VIDAURRE SANTOS\nPago Mes Actual S/ 47.72\nCaserío El muerto S/N Deuda total. S/ 113.96\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(294, 'recibo_40.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 99 Mes Actual Set-24\nOlmos/ Las Norias\nSANCHEZ MACO SANDRA M\nDatos del suministro de consumo Importes facturados\nLectura actual 9965 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 9907 Cargo Fijo S/ 3.53\nDiferencia Lectura 58 Energia activa S/ 43.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 47.03\nI.G.V S/ 8.47\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Mayo a Agosto S/ 484.70\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 61.00\nFecha de corte 20-Oct Deuda Total. S/ 545.70\nPeriodo comercial Set-24 Recibo N° 99\nSANCHEZ MACO SANDRA M\nPago Mes Actual S/ 61.00\nCaserío El muerto S/N Deuda total. S/ 545.70\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(295, 'recibo_41.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 98 Mes Actual Set-24\nOlmos/ Las Norias\nROQUE DE MIO CORINA\nDatos del suministro de consumo Importes facturados\nLectura actual 4638 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4607 Cargo Fijo S/ 3.53\nDiferencia Lectura 31 Energia activa S/ 23.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 26.78\nI.G.V S/ 4.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 37.10\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 98\nROQUE DE MIO CORINA\nPago Mes Actual S/ 37.10\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(296, 'recibo_42.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 97 Mes Actual Set-24\nOlmos/ Las Norias\nRODAS MONTENEGRO JULIO A\nDatos del suministro de consumo Importes facturados\nLectura actual 8697 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 8643 Cargo Fijo S/ 3.53\nDiferencia Lectura 54 Energia activa S/ 40.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 44.03\nI.G.V S/ 7.93\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 54.80\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 57.46\nFecha de corte 20-Oct Deuda Total. S/ 112.26\nPeriodo comercial Set-24 Recibo N° 97\nRODAS MONTENEGRO JULIO A\nPago Mes Actual S/ 57.46\nCaserío El muerto S/N Deuda total. S/ 112.26\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(297, 'recibo_43.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 96 Mes Actual Set-24\nOlmos/ Las Norias\nRAMOS SANTOS LUCIO\nDatos del suministro de consumo Importes facturados\nLectura actual 3383 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3359 Cargo Fijo S/ 3.53\nDiferencia Lectura 24 Energia activa S/ 18.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 21.53\nI.G.V S/ 3.88\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 30.91\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 96\nRAMOS SANTOS LUCIO\nPago Mes Actual S/ 30.91\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(298, 'recibo_44.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 95 Mes Actual Set-24\nOlmos/ Las Norias\nPUESTO DE SALUD\nDatos del suministro de consumo Importes facturados\nLectura actual 10260 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10180 Cargo Fijo S/ 3.10\nDiferencia Lectura 80 Energia activa S/ 68.00\nAporte a la Ley S/ 2.50\nSubtotal S/ 72.60\nI.G.V S/ 13.07\nCosto Actual de Kw S/ 0.85\nOtros gastos S/ 1.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 87.17\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 95\nPUESTO DE SALUD\nPago Mes Actual S/ 87.17\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(299, 'recibo_45.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 94 Mes Actual Set-24\nOlmos/ Las Norias\nPOZO COMUNAL EL MUERTO\nDatos del suministro de consumo Importes facturados\nLectura actual 126018 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 125080 Cargo Fijo S/ 3.53\nDiferencia Lectura 938 Energia activa S/ 703.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 707.03\nI.G.V S/ 127.27\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 839.80\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 94\nPOZO COMUNAL EL MUERTO\nPago Mes Actual S/ 839.80\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(300, 'recibo_46.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 93 Mes Actual Set-24\nOlmos/ Las Norias\nPLATAFORMA DEPORTIVA\nDatos del suministro de consumo Importes facturados\nLectura actual 1541 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1536 Cargo Fijo S/ 3.53\nDiferencia Lectura 5 Energia activa S/ 3.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 7.28\nI.G.V S/ 1.31\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 14.09\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 93\nPLATAFORMA DEPORTIVA\nPago Mes Actual S/ 14.09\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(301, 'recibo_47.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 92 Mes Actual Set-24\nOlmos/ Las Norias\nPEÑA SOPLOPUCO PAMELA\nDatos del suministro de consumo Importes facturados\nLectura actual 5864 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5832 Cargo Fijo S/ 3.53\nDiferencia Lectura 32 Energia activa S/ 24.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 27.53\nI.G.V S/ 4.96\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo + Junio a agosto S/ 171.00\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 37.99\nFecha de corte 20-Oct Deuda Total. S/ 208.99\nPeriodo comercial Set-24 Recibo N° 92\nPEÑA SOPLOPUCO PAMELA\nPago Mes Actual S/ 37.99\nCaserío El muerto S/N Deuda total. S/ 208.99\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(302, 'recibo_48.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 91 Mes Actual Set-24\nOlmos/ Las Norias\nPEÑA SOSA JAVIER\nDatos del suministro de consumo Importes facturados\nLectura actual 9064 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 9012 Cargo Fijo S/ 3.53\nDiferencia Lectura 52 Energia activa S/ 39.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 42.53\nI.G.V S/ 7.66\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 55.69\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 91\nPEÑA SOSA JAVIER\nPago Mes Actual S/ 55.69\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(303, 'recibo_49.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 89 Mes Actual Set-24\nOlmos/ Las Norias\nRAMOS YAJAHUANCA FLOR\nDatos del suministro de consumo Importes facturados\nLectura actual 2200 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2163 Cargo Fijo S/ 3.53\nDiferencia Lectura 37 Energia activa S/ 27.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 31.28\nI.G.V S/ 5.63\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 42.41\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 89\nRAMOS YAJAHUANCA FLOR\nPago Mes Actual S/ 42.41\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(304, 'recibo_50.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 88 Mes Actual Set-24\nOlmos/ Las Norias\nODAR SOPLOPUCO LUIS HUMBERTO\nDatos del suministro de consumo Importes facturados\nLectura actual 298 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 264 Cargo Fijo S/ 3.53\nDiferencia Lectura 34 Energia activa S/ 25.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 29.03\nI.G.V S/ 5.23\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 39.76\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 88\nODAR SOPLOPUCO LUIS HUMBERTO\nPago Mes Actual S/ 39.76\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(305, 'recibo_51.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 86 Mes Actual Set-24\nOlmos/ Las Norias\nOLAZABAL MAZA MANUEL\nDatos del suministro de consumo Importes facturados\nLectura actual 4636 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4618 Cargo Fijo S/ 3.53\nDiferencia Lectura 18 Energia activa S/ 13.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 17.03\nI.G.V S/ 3.07\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 25.60\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 86\nOLAZABAL MAZA MANUEL\nPago Mes Actual S/ 25.60\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(306, 'recibo_52.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 85 Mes Actual Set-24\nOlmos/ Las Norias\nOLAZABAL MAZA FELICIA\nDatos del suministro de consumo Importes facturados\nLectura actual 7781 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 7721 Cargo Fijo S/ 3.53\nDiferencia Lectura 60 Energia activa S/ 45.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 48.53\nI.G.V S/ 8.74\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 62.77\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 85\nOLAZABAL MAZA FELICIA\nPago Mes Actual S/ 62.77\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(307, 'recibo_53.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 84 Mes Actual Set-24\nOlmos/ Las Norias\nOLAZABAL GONZAGA EMELI MILAGRO\nDatos del suministro de consumo Importes facturados\nLectura actual 228 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 163 Cargo Fijo S/ 3.53\nDiferencia Lectura 65 Energia activa S/ 48.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 52.28\nI.G.V S/ 9.41\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Junio a Agosto S/ 223.26\nCuota medidor 2/3 S/ 50.00\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 67.19\nFecha de corte 20-Oct Deuda Total. S/ 340.45\nPeriodo comercial Set-24 Recibo N° 84\nOLAZABAL GONZAGA EMELI MILAGRO\nPago Mes Actual S/ 67.19\nCaserío El muerto S/N Deuda total. S/ 340.45\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(308, 'recibo_54.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 82 Mes Actual Set-24\nOlmos/ Las Norias\nODAR SOPLOPUCO DENIS\nDatos del suministro de consumo Importes facturados\nLectura actual 4791 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4737 Cargo Fijo S/ 3.53\nDiferencia Lectura 54 Energia activa S/ 40.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 44.03\nI.G.V S/ 7.93\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Marzo a Agosto S/ 302.29\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 57.46\nFecha de corte 20-Oct Deuda Total. S/ 359.75\nPeriodo comercial Set-24 Recibo N° 82\nODAR SOPLOPUCO DENIS\nPago Mes Actual S/ 57.46\nCaserío El muerto S/N Deuda total. S/ 359.75\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(309, 'recibo_55.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 81 Mes Actual Set-24\nOlmos/ Las Norias\nNUNURA VIUDA DE SOPLOPUCO MARIA\nDatos del suministro de consumo Importes facturados\nLectura actual 7252 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 7250 Cargo Fijo S/ 3.53\nDiferencia Lectura 2 Energia activa S/ 1.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 5.03\nI.G.V S/ 0.91\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 11.44\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 81\nNUNURA VIUDA DE SOPLOPUCO MARIA\nPago Mes Actual S/ 11.44\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(310, 'recibo_56.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 80 Mes Actual Set-24\nOlmos/ Las Norias\nNUNURA SOPLOPUCO PEDRO\nDatos del suministro de consumo Importes facturados\nLectura actual 942 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 939 Cargo Fijo S/ 3.53\nDiferencia Lectura 3 Energia activa S/ 2.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 5.78\nI.G.V S/ 1.04\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 12.32\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 80\nNUNURA SOPLOPUCO PEDRO\nPago Mes Actual S/ 12.32\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(311, 'recibo_57.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 79 Mes Actual Set-24\nOlmos/ Las Norias\nNUNURA ROQUE YAQUI\nDatos del suministro de consumo Importes facturados\nLectura actual 5327 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5256 Cargo Fijo S/ 3.53\nDiferencia Lectura 71 Energia activa S/ 53.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 56.78\nI.G.V S/ 10.22\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo S/ 47.66\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 72.50\nFecha de corte 20-Oct Deuda Total. S/ 120.16\nPeriodo comercial Set-24 Recibo N° 79\nNUNURA ROQUE YAQUI\nPago Mes Actual S/ 72.50\nCaserío El muerto S/N Deuda total. S/ 120.16\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(312, 'recibo_58.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 78 Mes Actual Set-24\nOlmos/ Las Norias\nNUNURA HERNANDEZ ELIO\nDatos del suministro de consumo Importes facturados\nLectura actual 2447 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2375 Cargo Fijo S/ 3.53\nDiferencia Lectura 72 Energia activa S/ 54.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 57.53\nI.G.V S/ 10.36\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 76.04\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 73.39\nFecha de corte 20-Oct Deuda Total. S/ 149.43\nPeriodo comercial Set-24 Recibo N° 78\nNUNURA HERNANDEZ ELIO\nPago Mes Actual S/ 73.39\nCaserío El muerto S/N Deuda total. S/ 149.43\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(313, 'recibo_59.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 77 Mes Actual Set-24\nOlmos/ Las Norias\nMONJA SOPLOPUCO MATEO\nDatos del suministro de consumo Importes facturados\nLectura actual 974 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 966 Cargo Fijo S/ 3.53\nDiferencia Lectura 8 Energia activa S/ 6.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 9.53\nI.G.V S/ 1.72\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 16.75\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 77\nMONJA SOPLOPUCO MATEO\nPago Mes Actual S/ 16.75\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(314, 'recibo_60.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 76 Mes Actual Set-24\nOlmos/ Las Norias\nMONJA SOPLOPUCO LUCIANO\nDatos del suministro de consumo Importes facturados\nLectura actual 6611 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 6544 Cargo Fijo S/ 3.53\nDiferencia Lectura 67 Energia activa S/ 50.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 53.78\nI.G.V S/ 9.68\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 45.07\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 68.96\nFecha de corte 20-Oct Deuda Total. S/ 114.03\nPeriodo comercial Set-24 Recibo N° 76\nMONJA SOPLOPUCO LUCIANO\nPago Mes Actual S/ 68.96\nCaserío El muerto S/N Deuda total. S/ 114.03\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(315, 'recibo_61.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 75 Mes Actual Set-24\nOlmos/ Las Norias\nMONJA SOPLOPUCO JOSE\nDatos del suministro de consumo Importes facturados\nLectura actual 8930 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 8887 Cargo Fijo S/ 3.53\nDiferencia Lectura 43 Energia activa S/ 32.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 35.78\nI.G.V S/ 6.44\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 47.72\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 75\nMONJA SOPLOPUCO JOSE\nPago Mes Actual S/ 47.72\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(316, 'recibo_62.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 74 Mes Actual Set-24\nOlmos/ Las Norias\nMONJA SOPLOPUCO FELIPE\nDatos del suministro de consumo Importes facturados\nLectura actual 13568 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 13499 Cargo Fijo S/ 3.53\nDiferencia Lectura 69 Energia activa S/ 51.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 55.28\nI.G.V S/ 9.95\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo + Julio - agosto S/ 176.67\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 70.73\nFecha de corte 20-Oct Deuda Total. S/ 247.40\nPeriodo comercial Set-24 Recibo N° 74\nMONJA SOPLOPUCO FELIPE\nPago Mes Actual S/ 70.73\nCaserío El muerto S/N Deuda total. S/ 247.40\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(317, 'recibo_63.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 72 Mes Actual Set-24\nOlmos/ Las Norias\nMONJA DE ROQUE JUANA\nDatos del suministro de consumo Importes facturados\nLectura actual 1137 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1120 Cargo Fijo S/ 3.53\nDiferencia Lectura 17 Energia activa S/ 12.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 16.28\nI.G.V S/ 2.93\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 24.71\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 72\nMONJA DE ROQUE JUANA\nPago Mes Actual S/ 24.71\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(318, 'recibo_64.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 71 Mes Actual Set-24\nOlmos/ Las Norias\nMONJA ALCANTARA PABLO TEODORO\nDatos del suministro de consumo Importes facturados\nLectura actual 3153 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3089 Cargo Fijo S/ 3.53\nDiferencia Lectura 64 Energia activa S/ 48.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 51.53\nI.G.V S/ 9.28\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 66.31\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 71\nMONJA ALCANTARA PABLO TEODORO\nPago Mes Actual S/ 66.31\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(319, 'recibo_65.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 70 Mes Actual Set-24\nOlmos/ Las Norias\nMIO SOPLOPUCO WALTER\nDatos del suministro de consumo Importes facturados\nLectura actual 12454 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12374 Cargo Fijo S/ 3.53\nDiferencia Lectura 80 Energia activa S/ 60.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 63.53\nI.G.V S/ 11.44\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 80.47\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 70\nMIO SOPLOPUCO WALTER\nPago Mes Actual S/ 80.47\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(320, 'recibo_66.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 69 Mes Actual Set-24\nOlmos/ Las Norias\nMIO SOPLOPUCO NESTOR RAUL\nDatos del suministro de consumo Importes facturados\nLectura actual 9640 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 9533 Cargo Fijo S/ 3.53\nDiferencia Lectura 107 Energia activa S/ 80.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 83.78\nI.G.V S/ 15.08\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 104.36\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 69\nMIO SOPLOPUCO NESTOR RAUL\nPago Mes Actual S/ 104.36\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL);
INSERT INTO `recibos` (`id`, `nombre`, `contenido`, `numero_recibo`, `deuda_anterior`, `pago_mes_actual`, `deuda_total`) VALUES
(321, 'recibo_67.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 68 Mes Actual Set-24\nOlmos/ Las Norias\nMIO SOPLOPUCO LILA ESTHER\nDatos del suministro de consumo Importes facturados\nLectura actual 19034 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 18927 Cargo Fijo S/ 3.53\nDiferencia Lectura 107 Energia activa S/ 80.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 83.78\nI.G.V S/ 15.08\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio - Agosto S/ 219.34\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 104.36\nFecha de corte 20-Oct Deuda Total. S/ 323.70\nPeriodo comercial Set-24 Recibo N° 68\nMIO SOPLOPUCO LILA ESTHER\nPago Mes Actual S/ 104.36\nCaserío El muerto S/N Deuda total. S/ 323.70\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(322, 'recibo_68.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 67 Mes Actual Set-24\nOlmos/ Las Norias\nMÍO SOPLOPUCO EBER ADOLFO\nDatos del suministro de consumo Importes facturados\nLectura actual 16500 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 16404 Cargo Fijo S/ 3.53\nDiferencia Lectura 96 Energia activa S/ 72.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 75.53\nI.G.V S/ 13.60\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 94.63\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 67\nMÍO SOPLOPUCO EBER ADOLFO\nPago Mes Actual S/ 94.63\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(323, 'recibo_69.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 66 Mes Actual Set-24\nOlmos/ Las Norias\nMIO ROQUE JOSE DEL CARMEN\nDatos del suministro de consumo Importes facturados\nLectura actual 12773 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12692 Cargo Fijo S/ 3.53\nDiferencia Lectura 81 Energia activa S/ 60.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 64.28\nI.G.V S/ 11.57\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 81.35\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 66\nMIO ROQUE JOSE DEL CARMEN\nPago Mes Actual S/ 81.35\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(324, 'recibo_70.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 65 Mes Actual Set-24\nOlmos/ Las Norias\nMIO ROQUE EUSEBIO\nDatos del suministro de consumo Importes facturados\nLectura actual 12286 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12259 Cargo Fijo S/ 3.53\nDiferencia Lectura 27 Energia activa S/ 20.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 23.78\nI.G.V S/ 4.28\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 143.42\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 33.56\nFecha de corte 20-Oct Deuda Total. S/ 176.98\nPeriodo comercial Set-24 Recibo N° 65\nMIO ROQUE EUSEBIO\nPago Mes Actual S/ 33.56\nCaserío El muerto S/N Deuda total. S/ 176.98\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(325, 'recibo_71.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 64 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MORE JOSE LUIS\nDatos del suministro de consumo Importes facturados\nLectura actual 1398 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1306 Cargo Fijo S/ 3.53\nDiferencia Lectura 92 Energia activa S/ 69.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 72.53\nI.G.V S/ 13.06\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 91.09\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 64\nMIO MORE JOSE LUIS\nPago Mes Actual S/ 91.09\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(326, 'recibo_72.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 63 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MONJA GRACIELA\nDatos del suministro de consumo Importes facturados\nLectura actual 3859 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3770 Cargo Fijo S/ 3.53\nDiferencia Lectura 89 Energia activa S/ 66.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 70.28\nI.G.V S/ 12.65\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Junio - Julio - Agosto S/ 325.86\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 88.43\nFecha de corte 20-Oct Deuda Total. S/ 414.29\nPeriodo comercial Set-24 Recibo N° 63\nMIO MONJA GRACIELA\nPago Mes Actual S/ 88.43\nCaserío El muerto S/N Deuda total. S/ 414.29\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(327, 'recibo_73.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 62 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MONJA ALONZO\nDatos del suministro de consumo Importes facturados\nLectura actual 4519 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4502 Cargo Fijo S/ 3.53\nDiferencia Lectura 17 Energia activa S/ 12.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 16.28\nI.G.V S/ 2.93\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 24.71\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 62\nMIO MONJA ALONZO\nPago Mes Actual S/ 24.71\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(328, 'recibo_74.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 61 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MACO MARLO\nDatos del suministro de consumo Importes facturados\nLectura actual 166 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 88 Cargo Fijo S/ 3.53\nDiferencia Lectura 78 Energia activa S/ 58.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 62.03\nI.G.V S/ 11.17\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio y agosto S/ 217.58\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 78.70\nFecha de corte 20-Oct Deuda Total. S/ 296.28\nPeriodo comercial Set-24 Recibo N° 61\nMIO MACO MARLO\nPago Mes Actual S/ 78.70\nCaserío El muerto S/N Deuda total. S/ 296.28\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(329, 'recibo_75.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 60 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MACO JOSE GABRIEL\nDatos del suministro de consumo Importes facturados\nLectura actual 10757 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10713 Cargo Fijo S/ 3.53\nDiferencia Lectura 44 Energia activa S/ 33.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 36.53\nI.G.V S/ 6.58\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 48.61\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 60\nMIO MACO JOSE GABRIEL\nPago Mes Actual S/ 48.61\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(330, 'recibo_76.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 59 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MACO HUMBERTO\nDatos del suministro de consumo Importes facturados\nLectura actual 12214 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12093 Cargo Fijo S/ 3.53\nDiferencia Lectura 121 Energia activa S/ 90.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 94.28\nI.G.V S/ 16.97\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio - agosto S/ 332.63\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 116.75\nFecha de corte 20-Oct Deuda Total. S/ 449.38\nPeriodo comercial Set-24 Recibo N° 59\nMIO MACO HUMBERTO\nPago Mes Actual S/ 116.75\nCaserío El muerto S/N Deuda total. S/ 449.38\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(331, 'recibo_77.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 58 Mes Actual Set-24\nOlmos/ Las Norias\nMIO MACO ELSY\nDatos del suministro de consumo Importes facturados\nLectura actual 4366 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4298 Cargo Fijo S/ 3.53\nDiferencia Lectura 68 Energia activa S/ 51.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 54.53\nI.G.V S/ 9.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio - Agosto S/ 158.28\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 69.85\nFecha de corte 20-Oct Deuda Total. S/ 228.13\nPeriodo comercial Set-24 Recibo N° 58\nMIO MACO ELSY\nPago Mes Actual S/ 69.85\nCaserío El muerto S/N Deuda total. S/ 228.13\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(332, 'recibo_78.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 57 Mes Actual Set-24\nOlmos/ Las Norias\nMIO GONZALES JUAN ARTURO\nDatos del suministro de consumo Importes facturados\nLectura actual 16907 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 16792 Cargo Fijo S/ 3.53\nDiferencia Lectura 115 Energia activa S/ 86.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 89.78\nI.G.V S/ 16.16\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 109.67\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 111.44\nFecha de corte 20-Oct Deuda Total. S/ 221.11\nPeriodo comercial Set-24 Recibo N° 57\nMIO GONZALES JUAN ARTURO\nPago Mes Actual S/ 111.44\nCaserío El muerto S/N Deuda total. S/ 221.11\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(333, 'recibo_79.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 56 Mes Actual Set-24\nOlmos/ Las Norias\nMIO BANCES JOSE ANTONIO\nDatos del suministro de consumo Importes facturados\nLectura actual 7078 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 7023 Cargo Fijo S/ 3.53\nDiferencia Lectura 55 Energia activa S/ 41.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 44.78\nI.G.V S/ 8.06\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 58.34\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 56\nMIO BANCES JOSE ANTONIO\nPago Mes Actual S/ 58.34\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(334, 'recibo_80.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 53 Mes Actual Set-24\nOlmos/ Las Norias\nASUNCIONA CHERO\nDatos del suministro de consumo Importes facturados\nLectura actual 10130 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10090 Cargo Fijo S/ 3.53\nDiferencia Lectura 40 Energia activa S/ 30.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 33.53\nI.G.V S/ 6.04\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 45.07\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 53\nASUNCIONA CHERO\nPago Mes Actual S/ 45.07\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(335, 'recibo_81.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 52 Mes Actual Set-24\nOlmos/ Las Norias\nMAZA SANCHEZ EUGENIO\nDatos del suministro de consumo Importes facturados\nLectura actual 10528 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10441 Cargo Fijo S/ 3.53\nDiferencia Lectura 87 Energia activa S/ 65.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 68.78\nI.G.V S/ 12.38\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 89.32\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 86.66\nFecha de corte 20-Oct Deuda Total. S/ 175.98\nPeriodo comercial Set-24 Recibo N° 52\nMAZA SANCHEZ EUGENIO\nPago Mes Actual S/ 86.66\nCaserío El muerto S/N Deuda total. S/ 175.98\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(336, 'recibo_82.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 51 Mes Actual Set-24\nOlmos/ Las Norias\nMAZA MIO MARIA TERESA\nDatos del suministro de consumo Importes facturados\nLectura actual 2661 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2601 Cargo Fijo S/ 3.53\nDiferencia Lectura 60 Energia activa S/ 45.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 48.53\nI.G.V S/ 8.74\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. SALD O + JUNIO S/ 118.87\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 62.77\nFecha de corte 20-Oct Deuda Total. S/ 181.64\nPeriodo comercial Set-24 Recibo N° 51\nMAZA MIO MARIA TERESA\nPago Mes Actual S/ 62.77\nCaserío El muerto S/N Deuda total. S/ 181.64\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(337, 'recibo_83.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 50 Mes Actual Set-24\nOlmos/ Las Norias\nMAZA CHERO TEODORO\nDatos del suministro de consumo Importes facturados\nLectura actual 8482 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 8443 Cargo Fijo S/ 3.53\nDiferencia Lectura 39 Energia activa S/ 29.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 32.78\nI.G.V S/ 5.90\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 44.18\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 50\nMAZA CHERO TEODORO\nPago Mes Actual S/ 44.18\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(338, 'recibo_84.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 49 Mes Actual Set-24\nOlmos/ Las Norias\nMAZA CHERO MARCELINO\nDatos del suministro de consumo Importes facturados\nLectura actual 14221 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 14167 Cargo Fijo S/ 3.53\nDiferencia Lectura 54 Energia activa S/ 40.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 44.03\nI.G.V S/ 7.93\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio y Agosto S/ 137.04\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 57.46\nFecha de corte 20-Oct Deuda Total. S/ 194.50\nPeriodo comercial Set-24 Recibo N° 49\nMAZA CHERO MARCELINO\nPago Mes Actual S/ 57.46\nCaserío El muerto S/N Deuda total. S/ 194.50\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(339, 'recibo_85.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 47 Mes Actual Set-24\nOlmos/ Las Norias\nMAYANGA BELLODAS ROXANA\nDatos del suministro de consumo Importes facturados\nLectura actual 2298 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2260 Cargo Fijo S/ 3.53\nDiferencia Lectura 38 Energia activa S/ 28.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 32.03\nI.G.V S/ 5.77\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo S/ 8.74\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 43.30\nFecha de corte 20-Oct Deuda Total. S/ 52.04\nPeriodo comercial Set-24 Recibo N° 47\nMAYANGA BELLODAS ROXANA\nPago Mes Actual S/ 43.30\nCaserío El muerto S/N Deuda total. S/ 52.04\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(340, 'recibo_86.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 46 Mes Actual Set-24\nOlmos/ Las Norias\nMACO SOPLOPUCO MATILDE\nDatos del suministro de consumo Importes facturados\nLectura actual 12197 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12190 Cargo Fijo S/ 3.53\nDiferencia Lectura 7 Energia activa S/ 5.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 8.78\nI.G.V S/ 1.58\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 15.86\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 46\nMACO SOPLOPUCO MATILDE\nPago Mes Actual S/ 15.86\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(341, 'recibo_87.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 45 Mes Actual Set-24\nOlmos/ Las Norias\nMACO SOPLOPUCO FLOR ISA\nDatos del suministro de consumo Importes facturados\nLectura actual 8417 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 8378 Cargo Fijo S/ 3.53\nDiferencia Lectura 39 Energia activa S/ 29.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 32.78\nI.G.V S/ 5.90\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 44.18\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 45\nMACO SOPLOPUCO FLOR ISA\nPago Mes Actual S/ 44.18\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(342, 'recibo_88.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 44 Mes Actual Set-24\nOlmos/ Las Norias\nMACO SOPLOPUCO FERNANDO\nDatos del suministro de consumo Importes facturados\nLectura actual 24048 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 23921 Cargo Fijo S/ 3.53\nDiferencia Lectura 127 Energia activa S/ 95.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 98.78\nI.G.V S/ 17.78\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 122.06\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 44\nMACO SOPLOPUCO FERNANDO\nPago Mes Actual S/ 122.06\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(343, 'recibo_89.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 43 Mes Actual Set-24\nOlmos/ Las Norias\nMACO SOPLOPUCO AUGUSTO\nDatos del suministro de consumo Importes facturados\nLectura actual 15557 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 15494 Cargo Fijo S/ 3.53\nDiferencia Lectura 63 Energia activa S/ 47.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 50.78\nI.G.V S/ 9.14\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 65.42\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 43\nMACO SOPLOPUCO AUGUSTO\nPago Mes Actual S/ 65.42\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(344, 'recibo_90.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 42 Mes Actual Set-24\nOlmos/ Las Norias\nMACO MONJA FERNANDO\nDatos del suministro de consumo Importes facturados\nLectura actual 3853 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3778 Cargo Fijo S/ 3.53\nDiferencia Lectura 75 Energia activa S/ 56.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 59.78\nI.G.V S/ 10.76\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 76.04\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 42\nMACO MONJA FERNANDO\nPago Mes Actual S/ 76.04\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(345, 'recibo_91.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 41 Mes Actual Set-24\nOlmos/ Las Norias\nLOCAL MULTIEVENTOS\nDatos del suministro de consumo Importes facturados\nLectura actual 647 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 647 Cargo Fijo S/ 3.53\nDiferencia Lectura 0 Energia activa S/ 0.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 3.53\nI.G.V S/ 0.64\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 9.67\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 41\nLOCAL MULTIEVENTOS\nPago Mes Actual S/ 9.67\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(346, 'recibo_92.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 40 Mes Actual Set-24\nOlmos/ Las Norias\nl.E.N•10183 \"E MUERTO\"\nDatos del suministro de consumo Importes facturados\nLectura actual 9101 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 9020 Cargo Fijo S/ 3.10\nDiferencia Lectura 81 Energia activa S/ 68.85\nAporte a la Ley S/ 2.50\nSubtotal S/ 73.45\nI.G.V S/ 13.22\nCosto Actual de Kw S/ 0.85\nOtros gastos S/ 1.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 88.17\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 40\nl.E.N•10183 \"E MUERTO\"\nPago Mes Actual S/ 88.17\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(347, 'recibo_93.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 39 Mes Actual Set-24\nOlmos/ Las Norias\nl.E.IN• 360 \" SANTO DOMINGO DE GUZMAN\"\nDatos del suministro de consumo Importes facturados\nLectura actual 10941 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10715 Cargo Fijo S/ 3.10\nDiferencia Lectura 226 Energia activa S/ 192.10\nAporte a la Ley S/ 2.50\nSubtotal S/ 196.70\nI.G.V S/ 35.41\nCosto Actual de Kw S/ 0.85\nOtros gastos S/ 1.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 233.61\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 39\nl.E.IN• 360 \" SANTO DOMINGO DE GUZMAN\"\nPago Mes Actual S/ 233.61\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(348, 'recibo_94.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 38 Mes Actual Set-24\nOlmos/ Las Norias\nIGLESIA MOVIMIENTO MISIONERO MUNDIAL\nDatos del suministro de consumo Importes facturados\nLectura actual 1613 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1606 Cargo Fijo S/ 3.53\nDiferencia Lectura 7 Energia activa S/ 5.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 8.78\nI.G.V S/ 1.58\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 15.86\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 38\nIGLESIA MOVIMIENTO MISIONERO MUNDIAL\nPago Mes Actual S/ 15.86\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(349, 'recibo_95.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 37 Mes Actual Set-24\nOlmos/ Las Norias\nHURTADO CHIRINOS EVA\nDatos del suministro de consumo Importes facturados\nLectura actual 3647 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3635 Cargo Fijo S/ 3.53\nDiferencia Lectura 12 Energia activa S/ 9.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 12.53\nI.G.V S/ 2.26\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 19.40\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 20.29\nFecha de corte 20-Oct Deuda Total. S/ 39.69\nPeriodo comercial Set-24 Recibo N° 37\nHURTADO CHIRINOS EVA\nPago Mes Actual S/ 20.29\nCaserío El muerto S/N Deuda total. S/ 39.69\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(350, 'recibo_96.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 35 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MONJA MOISES\nDatos del suministro de consumo Importes facturados\nLectura actual 3617 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3553 Cargo Fijo S/ 3.53\nDiferencia Lectura 64 Energia activa S/ 48.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 51.53\nI.G.V S/ 9.28\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Junio - Julio y agosto S/ 227.25\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 66.31\nFecha de corte 20-Oct Deuda Total. S/ 293.56\nPeriodo comercial Set-24 Recibo N° 35\nHERNANDEZ MONJA MOISES\nPago Mes Actual S/ 66.31\nCaserío El muerto S/N Deuda total. S/ 293.56\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(351, 'recibo_97.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 33 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MIO MIGUEL\nDatos del suministro de consumo Importes facturados\nLectura actual 1657 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1644 Cargo Fijo S/ 3.53\nDiferencia Lectura 13 Energia activa S/ 9.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 13.28\nI.G.V S/ 2.39\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 21.17\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 33\nHERNANDEZ MIO MIGUEL\nPago Mes Actual S/ 21.17\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(352, 'recibo_98.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 32 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ TORRES CESAR ALONSO\nDatos del suministro de consumo Importes facturados\nLectura actual 249 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 179 Cargo Fijo S/ 3.53\nDiferencia Lectura 70 Energia activa S/ 52.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 56.03\nI.G.V S/ 10.09\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 71.62\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 32\nHERNANDEZ TORRES CESAR ALONSO\nPago Mes Actual S/ 71.62\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(353, 'recibo_99.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 31 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MONJA ROSA ARACELY\nDatos del suministro de consumo Importes facturados\nLectura actual 2363 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2363 Cargo Fijo S/ 3.53\nDiferencia Lectura 0 Energia activa S/ 0.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 3.53\nI.G.V S/ 0.64\nCosto Actual de Kw S/ 0.75\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 4.17\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 31\nHERNANDEZ MONJA ROSA ARACELY\nPago Mes Actual S/ 4.17\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(354, 'recibo_100.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 30 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MONJA LUIS EDUARDO\nDatos del suministro de consumo Importes facturados\nLectura actual 1304 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1251 Cargo Fijo S/ 3.53\nDiferencia Lectura 53 Energia activa S/ 39.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 43.28\nI.G.V S/ 7.79\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 56.57\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 30\nHERNANDEZ MONJA LUIS EDUARDO\nPago Mes Actual S/ 56.57\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(355, 'recibo_101.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 29 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MONJA JHONY PERCY\nDatos del suministro de consumo Importes facturados\nLectura actual 3680 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3644 Cargo Fijo S/ 3.53\nDiferencia Lectura 36 Energia activa S/ 27.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 30.53\nI.G.V S/ 5.50\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 41.53\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 29\nHERNANDEZ MONJA JHONY PERCY\nPago Mes Actual S/ 41.53\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(356, 'recibo_102.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 28 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MONJA CESAR AUGUSTO\nDatos del suministro de consumo Importes facturados\nLectura actual 2920 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2861 Cargo Fijo S/ 3.53\nDiferencia Lectura 59 Energia activa S/ 44.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 47.78\nI.G.V S/ 8.60\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 61.88\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 28\nHERNANDEZ MONJA CESAR AUGUSTO\nPago Mes Actual S/ 61.88\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(357, 'recibo_103.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 27 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MONJA ANITA\nDatos del suministro de consumo Importes facturados\nLectura actual 1086 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1086 Cargo Fijo S/ 3.53\nDiferencia Lectura 0 Energia activa S/ 0.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 3.53\nI.G.V S/ 0.64\nCosto Actual de Kw S/ 0.75\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 4.17\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 27\nHERNANDEZ MONJA ANITA\nPago Mes Actual S/ 4.17\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(358, 'recibo_104.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 26 Mes Actual Set-24\nOlmos/ Las Norias\nHERNANDEZ MIO AUGUSTO\nDatos del suministro de consumo Importes facturados\nLectura actual 2969 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2966 Cargo Fijo S/ 3.53\nDiferencia Lectura 3 Energia activa S/ 2.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 5.78\nI.G.V S/ 1.04\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 12.32\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 26\nHERNANDEZ MIO AUGUSTO\nPago Mes Actual S/ 12.32\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(359, 'recibo_105.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 25 Mes Actual Set-24\nOlmos/ Las Norias\nGONZALES ENEQUE FANNY\nDatos del suministro de consumo Importes facturados\nLectura actual 2459 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2415 Cargo Fijo S/ 3.53\nDiferencia Lectura 44 Energia activa S/ 33.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 36.53\nI.G.V S/ 6.58\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo deuda + Agosto S/ 192.82\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 48.61\nFecha de corte 20-Oct Deuda Total. S/ 241.43\nPeriodo comercial Set-24 Recibo N° 25\nGONZALES ENEQUE FANNY\nPago Mes Actual S/ 48.61\nCaserío El muerto S/N Deuda total. S/ 241.43\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(360, 'recibo_106.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 24 Mes Actual Set-24\nOlmos/ Las Norias\nGONZAGA MACO LUZ MARINA\nDatos del suministro de consumo Importes facturados\nLectura actual 101 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 45 Cargo Fijo S/ 3.53\nDiferencia Lectura 56 Energia activa S/ 42.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 45.53\nI.G.V S/ 8.20\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 49.49\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 59.23\nFecha de corte 20-Oct Deuda Total. S/ 108.72\nPeriodo comercial Set-24 Recibo N° 24\nGONZAGA MACO LUZ MARINA\nPago Mes Actual S/ 59.23\nCaserío El muerto S/N Deuda total. S/ 108.72\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(361, 'recibo_107.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 23 Mes Actual Set-24\nOlmos/ Las Norias\nGONZAGA MACO ITALO\nDatos del suministro de consumo Importes facturados\nLectura actual 12361 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 12200 Cargo Fijo S/ 3.53\nDiferencia Lectura 161 Energia activa S/ 120.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 124.28\nI.G.V S/ 22.37\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 152.15\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 23\nGONZAGA MACO ITALO\nPago Mes Actual S/ 152.15\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(362, 'recibo_108.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 22 Mes Actual Set-24\nOlmos/ Las Norias\nFLORES SOSA SONIA MARIBEL\nDatos del suministro de consumo Importes facturados\nLectura actual 4505 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4459 Cargo Fijo S/ 3.53\nDiferencia Lectura 46 Energia activa S/ 34.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 38.03\nI.G.V S/ 6.85\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 50.38\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 22\nFLORES SOSA SONIA MARIBEL\nPago Mes Actual S/ 50.38\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(363, 'recibo_109.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 19 Mes Actual Set-24\nOlmos/ Las Norias\nEXALTACIÓN RAIMUNDO MARINO\nDatos del suministro de consumo Importes facturados\nLectura actual 4239 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 4212 Cargo Fijo S/ 3.53\nDiferencia Lectura 27 Energia activa S/ 20.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 23.78\nI.G.V S/ 4.28\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 33.56\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 19\nEXALTACIÓN RAIMUNDO MARINO\nPago Mes Actual S/ 33.56\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(364, 'recibo_110.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 18 Mes Actual Set-24\nOlmos/ Las Norias\nESPINOZA TORRES RINA\nDatos del suministro de consumo Importes facturados\nLectura actual 10776 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 10733 Cargo Fijo S/ 3.53\nDiferencia Lectura 43 Energia activa S/ 32.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 35.78\nI.G.V S/ 6.44\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 47.72\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 18\nESPINOZA TORRES RINA\nPago Mes Actual S/ 47.72\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(365, 'recibo_111.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 17 Mes Actual Set-24\nOlmos/ Las Norias\nCUZQUE TIQUILLAHUANCA EDER\nDatos del suministro de consumo Importes facturados\nLectura actual 1982 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1950 Cargo Fijo S/ 3.53\nDiferencia Lectura 32 Energia activa S/ 24.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 27.53\nI.G.V S/ 4.96\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Marzo a Agosto S/ 260.45\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 37.99\nFecha de corte 20-Oct Deuda Total. S/ 298.44\nPeriodo comercial Set-24 Recibo N° 17\nCUZQUE TIQUILLAHUANCA EDER\nPago Mes Actual S/ 37.99\nCaserío El muerto S/N Deuda total. S/ 298.44\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(366, 'recibo_112.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 16 Mes Actual Set-24\nOlmos/ Las Norias\nCUMPEN SIPION GLORIA ANITA\nDatos del suministro de consumo Importes facturados\nLectura actual 2828 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2761 Cargo Fijo S/ 3.53\nDiferencia Lectura 67 Energia activa S/ 50.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 53.78\nI.G.V S/ 9.68\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Multa corte S/ 20.00\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 68.96\nFecha de corte 20-Oct Deuda Total. S/ 88.96\nPeriodo comercial Set-24 Recibo N° 16\nCUMPEN SIPION GLORIA ANITA\nPago Mes Actual S/ 68.96\nCaserío El muerto S/N Deuda total. S/ 88.96\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(367, 'recibo_113.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 15 Mes Actual Set-24\nOlmos/ Las Norias\nCUMPEN PIZARRO JUAN MANUEL\nDatos del suministro de consumo Importes facturados\nLectura actual 2954 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2948 Cargo Fijo S/ 3.53\nDiferencia Lectura 6 Energia activa S/ 4.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 8.03\nI.G.V S/ 1.45\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Multa corte S/20 Agos S/ 34.09\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 14.98\nFecha de corte 20-Oct Deuda Total. S/ 49.07\nPeriodo comercial Set-24 Recibo N° 15\nCUMPEN PIZARRO JUAN MANUEL\nPago Mes Actual S/ 14.98\nCaserío El muerto S/N Deuda total. S/ 49.07\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(368, 'recibo_114.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 13 Mes Actual Set-24\nOlmos/ Las Norias\nCHAPA ALEJOS RAMON\nDatos del suministro de consumo Importes facturados\nLectura actual 7143 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 7101 Cargo Fijo S/ 3.53\nDiferencia Lectura 42 Energia activa S/ 31.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 35.03\nI.G.V S/ 6.31\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 46.84\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 13\nCHAPA ALEJOS RAMON\nPago Mes Actual S/ 46.84\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(369, 'recibo_115.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 12 Mes Actual Set-24\nOlmos/ Las Norias\nCERNA POLO JUANITA\nDatos del suministro de consumo Importes facturados\nLectura actual 1956 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1915 Cargo Fijo S/ 3.53\nDiferencia Lectura 41 Energia activa S/ 30.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 34.28\nI.G.V S/ 6.17\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Julio y Agosto S/ 99.87\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 45.95\nFecha de corte 20-Oct Deuda Total. S/ 145.82\nPeriodo comercial Set-24 Recibo N° 12\nCERNA POLO JUANITA\nPago Mes Actual S/ 45.95\nCaserío El muerto S/N Deuda total. S/ 145.82\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(370, 'recibo_116.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 10 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES TESEN SEGUNDO JACINTO\nDatos del suministro de consumo Importes facturados\nLectura actual 14394 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 14240 Cargo Fijo S/ 3.53\nDiferencia Lectura 154 Energia activa S/ 115.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 119.03\nI.G.V S/ 21.43\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 145.96\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 10\nBENITES TESEN SEGUNDO JACINTO\nPago Mes Actual S/ 145.96\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(371, 'recibo_117.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 9 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES TESEN SIMON\nDatos del suministro de consumo Importes facturados\nLectura actual 8690 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 8679 Cargo Fijo S/ 3.53\nDiferencia Lectura 11 Energia activa S/ 8.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 11.78\nI.G.V S/ 2.12\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 19.40\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 9\nBENITES TESEN SIMON\nPago Mes Actual S/ 19.40\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(372, 'recibo_118.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 8 Mes Actual Set-24\nOlmos/ Las Norias\nMACO SOPLOPUCO PAULA\nDatos del suministro de consumo Importes facturados\nLectura actual 16756 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 16612 Cargo Fijo S/ 3.53\nDiferencia Lectura 144 Energia activa S/ 108.00\nAporte a la Ley S/ 2.00\nSubtotal S/ 111.53\nI.G.V S/ 20.08\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Abril a Agosto S/ 571.02\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 137.11\nFecha de corte 20-Oct Deuda Total. S/ 708.13\nPeriodo comercial Set-24 Recibo N° 8\nMACO SOPLOPUCO PAULA\nPago Mes Actual S/ 137.11\nCaserío El muerto S/N Deuda total. S/ 708.13\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL),
(373, 'recibo_119.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 7 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES TESEN JUANA ROSA\nDatos del suministro de consumo Importes facturados\nLectura actual 5744 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 5718 Cargo Fijo S/ 3.53\nDiferencia Lectura 26 Energia activa S/ 19.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 23.03\nI.G.V S/ 4.15\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 32.68\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 7\nBENITES TESEN JUANA ROSA\nPago Mes Actual S/ 32.68\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(374, 'recibo_120.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 6 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES TESEN JUAN JOSE\nDatos del suministro de consumo Importes facturados\nLectura actual 14713 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 14656 Cargo Fijo S/ 3.53\nDiferencia Lectura 57 Energia activa S/ 42.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 46.28\nI.G.V S/ 8.33\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 60.11\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 6\nBENITES TESEN JUAN JOSE\nPago Mes Actual S/ 60.11\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(375, 'recibo_121.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 5 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES MONJA ELIO SIMON\nDatos del suministro de consumo Importes facturados\nLectura actual 1635 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1582 Cargo Fijo S/ 3.53\nDiferencia Lectura 53 Energia activa S/ 39.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 43.28\nI.G.V S/ 7.79\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Saldo + Junio a Agosto S/ 221.48\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 56.57\nFecha de corte 20-Oct Deuda Total. S/ 278.05\nPeriodo comercial Set-24 Recibo N° 5\nBENITES MONJA ELIO SIMON\nPago Mes Actual S/ 56.57\nCaserío El muerto S/N Deuda total. S/ 278.05\nCorte Programado 20 OCTUBRE.', NULL, NULL, NULL, NULL),
(376, 'recibo_122.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 4 Mes Actual Set-24\nOlmos/ Las Norias\nBENITES MIO JOSE LUIS\nDatos del suministro de consumo Importes facturados\nLectura actual 3000 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2969 Cargo Fijo S/ 3.53\nDiferencia Lectura 31 Energia activa S/ 23.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 26.78\nI.G.V S/ 4.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 37.10\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 4\nBENITES MIO JOSE LUIS\nPago Mes Actual S/ 37.10\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(377, 'recibo_123.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 3 Mes Actual Set-24\nOlmos/ Las Norias\nBELLODAS PUPUCHE URSULA\nDatos del suministro de consumo Importes facturados\nLectura actual 2664 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 2661 Cargo Fijo S/ 3.53\nDiferencia Lectura 3 Energia activa S/ 2.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 5.78\nI.G.V S/ 1.04\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 14.09\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 12.32\nFecha de corte 20-Oct Deuda Total. S/ 26.41\nPeriodo comercial Set-24 Recibo N° 3\nBELLODAS PUPUCHE URSULA\nPago Mes Actual S/ 12.32\nCaserío El muerto S/N Deuda total. S/ 26.41\nCorte Programado 20 OCTUBRE.', NULL, NULL, NULL, NULL),
(378, 'recibo_124.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 2 Mes Actual Set-24\nOlmos/ Las Norias\nBEJARANO CHANTA JORGE LUIS\nDatos del suministro de consumo Importes facturados\nLectura actual 670 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 669 Cargo Fijo S/ 3.53\nDiferencia Lectura 1 Energia activa S/ 0.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 4.28\nI.G.V S/ 0.77\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 10.55\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 2\nBEJARANO CHANTA JORGE LUIS\nPago Mes Actual S/ 10.55\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(379, 'recibo_125.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 1 Mes Actual Set-24\nOlmos/ Las Norias\nASALDE HERNANDEZ LUIS A\nDatos del suministro de consumo Importes facturados\nLectura actual 1276 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 1210 Cargo Fijo S/ 3.53\nDiferencia Lectura 66 Energia activa S/ 49.50\nAporte a la Ley S/ 2.00\nSubtotal S/ 53.03\nI.G.V S/ 9.55\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Mayo a Agosto S/ 333.13\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 68.08\nFecha de corte 20-Oct Deuda Total. S/ 401.21\nPeriodo comercial Set-24 Recibo N° 1\nASALDE HERNANDEZ LUIS A\nPago Mes Actual S/ 68.08\nCaserío El muerto S/N Deuda total. S/ 401.21\nCorte Programado 20 OCTUBRE.', NULL, NULL, NULL, NULL),
(380, 'recibo_126.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 54 Mes Actual Set-24\nOlmos/ Las Norias\nMIO SOPLOPUCO MARY\nDatos del suministro de consumo Importes facturados\nLectura actual 8785 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 8704 Cargo Fijo S/ 3.53\nDiferencia Lectura 81 Energia activa S/ 60.75\nAporte a la Ley S/ 2.00\nSubtotal S/ 64.28\nI.G.V S/ 11.57\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 81.35\nFecha de corte 20-Oct\nPeriodo comercial Set-24 Recibo N° 54\nMIO SOPLOPUCO MARY\nPago Mes Actual S/ 81.35\nCaserío El muerto S/N\nDisfrute del servicio pagando su recibo antes de la fecha de corte.', NULL, NULL, NULL, NULL),
(381, 'recibo_127.pdf', 'Comité de Electrificación Las Norias\nRecibo N° 20 Mes Actual Set-24\nOlmos/ Las Norias\nFERNANDEZ DÍAZ DEILER\nDatos del suministro de consumo Importes facturados\nLectura actual 3796 Recibo por consumo: 01- 30 Setiembre\nLectura anterior 3765 Cargo Fijo S/ 3.53\nDiferencia Lectura 31 Energia activa S/ 23.25\nAporte a la Ley S/ 2.00\nSubtotal S/ 26.78\nI.G.V S/ 4.82\nCosto Actual de Kw S/ 0.75\nOtros gastos S/ 5.50\nDeuda anterior. Agosto S/ 37.99\nFecha vencimiento 15-Oct\nPago Mes Actual S/ 37.10\nFecha de corte 20-Oct Deuda Total. S/ 75.09\nPeriodo comercial Set-24 Recibo N° 20\nFERNANDEZ DÍAZ DEILER\nPago Mes Actual S/ 37.10\nCaserío El muerto S/N Deuda total. S/ 75.09\nCorte Programado 20 Octubre.', NULL, NULL, NULL, NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `recibos`
--
ALTER TABLE `recibos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `recibos`
--
ALTER TABLE `recibos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=382;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
